-- ============================================================================
-- KARIS OS™ UNIFIED ENTERPRISE & DIGITAL ECONOMY PLATFORM
-- Migration 007: Treasury Engine, KRT Token Economy & Credit Lending Engine
-- Enforces: Section 6 (KRT), Section 12 (Treasury), Section 18 (KRT Economy), Section 19 (Credit)
-- Rule 3: No Credit Approval -> No Credit Purchase
-- ============================================================================

-- 1. TREASURY RESERVES & REWARD POOLS
CREATE TABLE IF NOT EXISTS treasury_reserves (
    reserve_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(organization_id),
    wallet_id UUID NOT NULL REFERENCES wallets(wallet_id),
    account_type VARCHAR(50) NOT NULL CHECK (account_type IN (
        'RESERVE_WALLET', 'LIQUIDITY_WALLET', 'REWARD_POOL', 'OPERATIONS_WALLET', 'EMERGENCY_RESERVE', 'INVESTMENT_RESERVE'
    )),
    asset_type VARCHAR(20) NOT NULL CHECK (asset_type IN ('KES', 'KRT')),
    target_reserve_ratio NUMERIC(5, 2) DEFAULT 20.00 NOT NULL, -- Percentage reserve target
    current_liquidity NUMERIC(20, 6) DEFAULT 0.000000 NOT NULL,
    max_supply_limit NUMERIC(20, 6), -- e.g., KRT maximum token cap
    circulating_supply NUMERIC(20, 6) DEFAULT 0.000000 NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'HEALTHY' CHECK (status IN ('HEALTHY', 'REBALANCING_REQUIRED', 'CRITICAL_LIQUIDITY')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. KRT MINT & BURN AUDIT LOG
CREATE TABLE IF NOT EXISTS krt_token_ledger (
    token_operation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_id UUID NOT NULL REFERENCES event_store(event_id),
    treasury_reserve_id UUID NOT NULL REFERENCES treasury_reserves(reserve_id),
    target_wallet_id UUID REFERENCES wallets(wallet_id),
    operation_type VARCHAR(50) NOT NULL CHECK (operation_type IN (
        'TOKEN_MINTED', 'TOKEN_GRANTED', 'TOKEN_BURNED', 'TOKEN_REDEEMED', 'TOKEN_EXPIRED'
    )),
    trigger_reason VARCHAR(100) NOT NULL CHECK (trigger_reason IN (
        'PURCHASE_COMPLETED', 'DELIVERY_COMPLETED', 'REFERRAL_CONFIRMED',
        'LOAN_REPAID', 'INVESTMENT_COMPLETED', 'LOYALTY_BONUS_GRANTED',
        'PROMOTION_TRIGGERED', 'DISCOUNT_REDEMPTION', 'CAMPAIGN_REDEMPTION', 'EXPIRY_BURN'
    )),
    amount NUMERIC(20, 6) NOT NULL CHECK (amount > 0),
    previous_circulating_supply NUMERIC(20, 6) NOT NULL,
    new_circulating_supply NUMERIC(20, 6) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    audit_hash VARCHAR(64) NOT NULL
);

-- 3. CREDIT & LENDING PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS lending_products (
    product_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(organization_id),
    lender_identity_id UUID NOT NULL REFERENCES identities(identity_id), -- e.g., Bank, Financial Institution, Platform
    product_code VARCHAR(100) UNIQUE NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    min_amount_kes NUMERIC(15, 2) NOT NULL,
    max_amount_kes NUMERIC(15, 2) NOT NULL,
    interest_rate_pct NUMERIC(5, 2) NOT NULL,
    duration_days INT NOT NULL,
    eligibility_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 4. CREDIT APPLICATIONS & LOANS (Enforcing Rule 3: No Credit Approval -> No Credit Purchase)
CREATE TABLE IF NOT EXISTS credit_applications (
    application_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(organization_id),
    borrower_identity_id UUID NOT NULL REFERENCES identities(identity_id),
    lending_product_id UUID NOT NULL REFERENCES lending_products(product_id),
    requested_amount_kes NUMERIC(15, 2) NOT NULL CHECK (requested_amount_kes > 0),
    approved_amount_kes NUMERIC(15, 2) DEFAULT 0.00,
    ai_risk_score NUMERIC(5, 2), -- Generated by AI Risk Engine
    risk_assessment_summary TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'APPLICATION_SUBMITTED' CHECK (status IN (
        'APPLICATION_SUBMITTED', 'RISK_EVALUATION', 'CREDIT_APPROVED', 'CREDIT_REJECTED',
        'FUNDS_ALLOCATED', 'ACTIVE_REPAYMENT', 'LOAN_CLOSED', 'DELINQUENT'
    )),
    approved_by_identity_id UUID REFERENCES identities(identity_id),
    approval_timestamp TIMESTAMP WITH TIME ZONE,
    disbursement_event_id UUID REFERENCES event_store(event_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. LOAN REPAYMENT SCHEDULE & LOGS
CREATE TABLE IF NOT EXISTS loan_repayments (
    repayment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID NOT NULL REFERENCES credit_applications(application_id) ON DELETE CASCADE,
    payer_identity_id UUID NOT NULL REFERENCES identities(identity_id),
    amount_paid_kes NUMERIC(15, 2) NOT NULL CHECK (amount_paid_kes > 0),
    repayment_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payment_reference VARCHAR(100),
    event_id UUID NOT NULL REFERENCES event_store(event_id),
    remaining_balance_kes NUMERIC(15, 2) NOT NULL,
    krt_reward_earned NUMERIC(15, 2) DEFAULT 0.00
);

CREATE INDEX idx_krt_token_ledger_type ON krt_token_ledger(operation_type, trigger_reason);
CREATE INDEX idx_credit_applications_borrower ON credit_applications(borrower_identity_id, status);
CREATE INDEX idx_loan_repayments_app ON loan_repayments(application_id);
